spring.application.name=JournalApplication
server.port=9090

spring.mongodb.uri=mongodb://localhost:27017/journaldb

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword

#logging.level.org.mongodb.driver=DEBUG
#logging.level.org.springframework.data.mongodb=DEBUG

#
#logging.level.org.mongodb.driver=DEBUG
#logging.level.org.springframework.data.mongodb=DEBUG
#
#





#mongodb://localhost:27017













